### ISSUE TITLE
请问能否支持clash配置中的规则甚至规则集

### ISSUE THREAD

**Issue by seepine** [xmdhs/clash2singbox#25]
例如规则
<img width="153" alt="image" src="https://github.com/user-attachments/assets/622adc22-10a4-49c7-ba1d-9401a487a108" />

甚至规则集合
<img width="659" alt="image" src="https://github.com/user-attachments/assets/d4caecea-94f8-4713-b455-3f692a849eeb" />

**Comment by xmdhs** [comment]
clash 的规则因为 clash 本身缺少一些关键功能，导致规则不适合 sing-box。

sing-box 也有自己的规则集，也有相关的转换完成的项目，如 https://github.com/MetaCubeX/meta-rules-dat/tree/sing

如果有复杂的按节点分流，可以用 https://github.com/xmdhs/clash2sfa
