### ISSUE TITLE
套娃

### ISSUE THREAD

**Issue by ldh1983** [xmdhs/clash2singbox#7]
请问怎么套娃，比如我添加了一个香港代理组，我另一个代理组需要包含香港代理组。谢谢。

**Comment by xmdhs** [comment]
没有明白你的意思

**Comment by ldh1983** [comment]
就是代理组里有代理组，目前您的转换，在自定义 urltest / selector里无论怎么编辑转换出来后代理组只有节点，没办法包含代理组。

**Comment by xmdhs** [comment]
你可能需要的是 https://clash2sfa-xmdhs.koyeb.app/ 里的 `自定义 urltest / selector`

配置文件模板中添加的节点，包括 urltest / selector 也会保留，你可以在这里面添加上面自定义的 tag 名
