### ISSUE TITLE
hy2生成的配置文件使用的mixed需要root权限

### ISSUE THREAD

**Issue by snakexgc** [xmdhs/clash2singbox#8]
## bug 成因
生成的文件使用的是mixed，这个需要安卓拥有root权限或者ios有特权，如图：  

![image](https://github.com/xmdhs/clash2singbox/assets/78722169/347f0166-a2a4-4c4a-8db5-65d9a8df30db)
  

经过实测在安卓机上不能使用，会提示权限不足  

![Screenshot_2023-09-29-17-09-01-753_io nekohasekai](https://github.com/xmdhs/clash2singbox/assets/78722169/571fd8e3-477d-42ab-93c1-35e0c387ea70)

**Comment by xmdhs** [comment]
sfa 建议你用 https://github.com/xmdhs/clash2sfa 

以及你可以直接从模板中删除 `"set_system_proxy": true,`
